version: "3.9"
services:
  web:
    image: nginx:1.27-alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./code:/usr/share/nginx/html
  php:
    image: php:8.2-fpm
    container_name: lab2_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
